services:
  db:
    image: mysql:9.3.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_USER: ${MYSQL_UNAME}
      MYSQL_PASSWORD: ${MYSQL_PWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
    volumes:
      - ./data/mysql/:/var/lib/mysql/

  gitea:
    image: gitea/gitea:1.23
    container_name: gitea
    restart: unless-stopped
    environment:
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: db:3306
      GITEA__database__NAME: ${MYSQL_DBNAME}
      GITEA__database__USER: ${MYSQL_UNAME}
      GITEA__database__PASSWD: ${MYSQL_PWORD}

      GITEA_ADMIN_UNAME: ${GITEA_ADMIN_UNAME}
      GITEA_ADMIN_EMAIL: ${GITEA_ADMIN_EMAIL}
      GITEA_ADMIN_PWORD: ${GITEA_ADMIN_PWORD}
    command: [ "bash", "/opt/entrypoint.sh" ]
    volumes:
      - ./data/gitea/:/data/
      - ./data/shared/:/shared/
      - ./gitea/app.ini:/etc/app.ini:ro
      - ./gitea/entrypoint.sh:/opt/entrypoint.sh:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_WEB_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    depends_on:
      - db

  runner:
    image: gitea/act_runner:0.2.11-dind-rootless
    container_name: runner
    restart: unless-stopped
    #      \/ lol
    user: root
    privileged: true
    entrypoint: [ "bash", "/entrypoint" ]
    environment:
      GITEA_INSTANCE_URL: "http://172.20.0.48:3000"
      GITEA_RUNNER_NAME: "runner"

    volumes:
      - ./runner/entrypoint.sh:/entrypoint:ro
      - ./runner/supervisord.conf:/etc/supervisord.conf:ro
      - ./data/shared/:/shared/
      - ./data/runner/data/:/data/
      - ./data/runner/docker/:/var/lib/docker/
    depends_on:
      - db
      - gitea
