services:
  db:
    image: mysql:9.3.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea
      MYSQL_DATABASE: gitea
    volumes:
      - ./data/mysql/:/var/lib/mysql/

  gitea:
    image: gitea/gitea:1.23
    container_name: gitea
    restart: unless-stopped
    environment:
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: db:3306
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: gitea
    volumes:
      - ./data/gitea/:/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_WEB_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    depends_on:
      - db

  runner:
    image: gitea/act_runner:0.2.11-dind-rootless
    container_name: runner
    restart: unless-stopped
    #      \/ lol
    user: root
    entrypoint: [ "bash", "/entrypoint" ]
    environment:
      # CONFIG_FILE: /config.yaml
      GITEA_SERVER_NAME: gitea
      GITEA_INSTANCE_URL: "http://172.20.0.48:3000"
      GITEA_RUNNER_NAME: "runner"
    volumes:
      - ./runner/entrypoint.sh:/entrypoint:ro
      - ./data/runner/:/data/
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - gitea
